### ISSUE TITLE
there is an error building with gradle

### ISSUE THREAD

**Issue by chucky86boy** [skoumalcz/fragment-back#3]
Error:Failed to resolve: annotationProcessor
Error:(142, 13) Failed to resolve: net.skoumal.fragmentback:fragment-back:0.2.0

I am using buildToolsVersion 25.0.0

**Comment by gingo** [comment]
Looks like the library was kicked out from jcentral for some reason. I just submitted request to put it back. We have to wait few hours for response ...

Sorry for inconvenience.

**Comment by gingo** [comment]
Approved! Please use v0.2.2 in your Gradle file.
