### ISSUE TITLE
How does this work with priority increment/decrement

### ISSUE THREAD

**Issue by erikswed** [skoumalcz/fragment-back#6]
Thanks for interesting lib, How does this work:
 We support five fragment priorities for ordering back-pressed event delivery
This should cover majority of use-cases. If you need more fine control over priorities, feel free to increase or decrease priority by number constant. Just keep increment/decrement under 100.

What am I increment/decrement?

**Comment by gingo** [comment]
You can increase/decrease fragment priority by incrementing/decrementing in `getBackPriority()` method.

    public int getBackPriority() {
        // little bit higher than normal priority
        return NORMAL_BACK_PRIORITY + 1;
    }

**Comment by erikswed** [comment]
sorry I´m a noob I dont understand what is getting higher or lower , what is fragment priority?

**Comment by gingo** [comment]
Imagine you have 5 `BackFragments` in your `Activity`. Now when user hits hardware back button `BackFragments` are ordered by priority and the one with highest priority is notified about back-press at first.

**Comment by erikswed** [comment]
Thanks for taking your time, this was useful info

**Comment by gingo** [comment]
Sorry I missed your comment. You can simply use isResumed() method (https://developer.android.com/reference/android/app/Fragment.html#isResumed()) to detect if your fragment is currently active.
